PROGRAM OPENMP_PI_ATOMIC
    INTEGER I, N
    DOUBLE PRECISION X, STEP, PI /0.0/, THREAD_SUM /0.0/, SUM /0.0/
    N = 100000000
    STEP = 1.57079632675/N
!$OMP PARALLEL PRIVATE(X) FIRSTPRIVATE(THREAD_SUM)
!$OMP DO
    DO I=1, N
      X = (I-0.5)*STEP
      THREAD_SUM = THREAD_SUM + sin(x)*log(sin(X))
    END DO
!$OMP END DO
!$OMP ATOMIC
    SUM = SUM + THREAD_SUM
!$OMP END PARALLEL
    PI = SUM * STEP
    print*, PI
END
