PROGRAM OPENMP_PI_LOCK
    INCLUDE 'omp_lib.h'
    INTEGER I, N, TID
    INTEGER(OMP_LOCK_KIND) LOCK
    DOUBLE PRECISION X, STEP, PI /0.0/, THREAD_SUM /0.0/
    N= 100000000
    STEP = 1.57079632675/N
    CALL OMP_INIT_LOCK(LOCK)
!$OMP PARALLEL PRIVATE(X) FIRSTPRIVATE(THREAD_SUM)
!$OMP DO
    DO I=1, N
      X = (I-0.5)*STEP
      THREAD_SUM = THREAD_SUM + sin(x)*log(sin(X))
    END DO
!$OMP END DO
    CALL OMP_SET_LOCK(LOCK)
    PI = PI + STEP * THREAD_SUM
    CALL OMP_UNSET_LOCK(LOCK)
!$OMP END PARALLEL
    CALL OMP_DESTROY_LOCK(LOCK)
    print*, PI
END