PROGRAM OPENMP_PI_CRITICAL
    INTEGER I, N
    DOUBLE PRECISION X, STEP, PI /0.0/, SUM /0.0/
    N = 100000000
    STEP = 1.57079632675/N
!$OMP PARALLEL PRIVATE(X) FIRSTPRIVATE(SUM)
!$OMP DO
    DO I=1, N
      X = (I-0.5)*STEP
      SUM = SUM + sin(x)*log(sin(X))
    END DO
!$OMP END DO
!$OMP CRITICAL
    PI = PI + STEP * SUM
!$OMP END CRITICAL
!$OMP END PARALLEL
    print*, PI
END
