PROGRAM OPENMP_PI_SPMD
    INCLUDE 'omp_lib.h'
    INTEGER I, N, NTHREADS, TID, ISTART, IEND
    DOUBLE PRECISION X, STEP, PI /0.0/, THREAD_SUM /0.0/
    PARAMETER (N=100000000)
    STEP = 1.57079632675/N
!$OMP PARALLEL IF(N .GE. 100)
!$OMP&  PRIVATE(TID, X, I, ISTART, IEND) REDUCTION(+:THREAD_SUM)
    TID = OMP_GET_THREAD_NUM()
    IF (TID.EQ.0) NTHREADS = OMP_GET_NUM_THREADS() 
    ISTART = TID+1
    IEND = N
    DO I=ISTART, IEND, NTHREADS
      X = (I-0.5)*STEP
      THREAD_SUM = THREAD_SUM + sin(X)*log(sin(X))
    END DO
!$OMP END PARALLEL
    PI = STEP * THREAD_SUM
    PRINT *, 'PI = ', PI
END